version: '3'

services:
  rabbitmq:
    container_name: vogi-rabbitmq
    image: rabbitmq:management
    ports:
      - 15672:15672
      - 5672:5672
    volumes:
      - ./data:/var/lib/rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: '${RABBITMQ_DEFAULT_USER:-admin}'
      RABBITMQ_DEFAULT_PASS: '${RABBITMQ_DEFAULT_PASS:-admin}'
